site_name: kollega
site_url: https://eugenia06.github.io/ev_demo1
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
site_author: Turtle Tortilla
copyright: Turtle Tortilla, etoturtle, 2026
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - css/extra.css